### ISSUE TITLE
ImGuiItemStatusFlags errors when building

### ISSUE THREAD

**Issue by santaclose** [ocornut/imgui_test_engine#27]
I'm trying to set this up to test https://github.com/santaclose/ste
I tried to follow this guide: https://github.com/ocornut/imgui_test_engine/wiki/Setting-Up

> Add to your imconfig file #include "imgui_te_imconfig.h or add equivalent configuration directives.

I'm not sure what you mean by "your imconfig file" and I don't think I have one, but I tried to add the configuration to one of my cpp files:
![image](https://github.com/ocornut/imgui_test_engine/assets/6496455/571aad60-24e1-488e-82b6-62e0e3b88df2)

And don't know where the `ImGuiItemStatusFlags` identifiers are supposed to be defined 🤔 
![image](https://github.com/ocornut/imgui_test_engine/assets/6496455/53484ef1-6581-4bb8-9532-c3d4d3505470)

Thanks in advance.

**Comment by ocornut** [comment]
Imconfig.h is the main file to configure dear imgui:
https://github.com/ocornut/imgui/blob/master/imconfig.h

You can either modify the file in imgui/ directory or set the define globally in your build process to redirect it to a file of your choice.

**Comment by santaclose** [comment]
thanks for the info! building fine now.
