### ISSUE TITLE
Possibilities for other code coverage test report exporters

### ISSUE THREAD

**Issue by MohitSethi99** [ocornut/imgui_test_engine#3]
I use sonarcloud for project analysis and stuff and junit isn't supported there for C/C++ code coverage.
Is there possibility to support exporters in any of the following formats:

VS Coverage
LLVM-COV
GCOV

**Comment by ocornut** [comment]
I am not sure I understand how Code Coverage relates to Test Results?
Code Coverage and Testing seems to be different concepts ?
Could you elaborate ?

**Comment by MohitSethi99** [comment]
As you can see here: https://docs.sonarcloud.io/enriching/test-coverage/c-c-objective-c-test-coverage/
They support selective report formats and junit isn't one of them.

**Comment by PathogenDavid** [comment]
Test results and code coverage are generally reported and handled completely independently. (At a low level at least, you might get aggregated reports out of some testing frameworks.)

Code coverage is generally done through instrumentation and shouldn't require the cooperation of the test engine.

**Comment by ocornut** [comment]
The page you linked to under “ Test Execution Parameters “ says CPPUnit which seems to be JUnit format. 
Anyhow, exporters are easy to write. If something is missing you can write one.

**Comment by MohitSethi99** [comment]
Okay, great! If it works I'll inform here and close the issue by next weekend.
