### ISSUE TITLE
CaptureScreenshotWindow on docked window leads to a black capture

### ISSUE THREAD

**Issue by pthom** [ocornut/imgui_test_engine#34]
Hello Omar,

Since the capture hides all other windows, the parent window of a docked window will be hidden and as a result, the screenshot will be black.

There is no emergency. I do not need that at the moment.

### Steps to reproduce

Add and call this inside *app_minimal_main.cpp*
```cpp
void ShowDockedWindows()
{
    // Create parent DockSpace inside a window
    auto dockSpaceId =  ImGui::GetID("ParentDockSpace");
    ImGui::SetNextWindowSize(ImVec2(400.f, 400.f));
    ImGui::Begin("ParentDockWindow");
    ImGui::DockSpace(dockSpaceId, ImVec2(0.0f, 0.0f), ImGuiDockNodeFlags_PassthruCentralNode);

    // Create two initially docked windows

    ImGui::SetNextWindowDockID(dockSpaceId, ImGuiCond_Appearing);
    ImGui::Begin("Window1");
    ImGui::Text("Window1");
    ImGui::End();

    ImGui::SetNextWindowDockID(dockSpaceId, ImGuiCond_Appearing);
    ImGui::Begin("Window2");
    ImGui::Text("Window2");
    ImGui::End();

    // End DockSpace's window
    ImGui::End();
}
```

Add this inside *app_minimal_tests.cpp*:

```cpp
    t = IM_REGISTER_TEST(e, "demo_tests", "capture_docked_window");
    t->TestFunc = [](ImGuiTestContext* ctx)
    {
        ctx->ItemClick("Window1");
        ctx->CaptureScreenshotWindow("Window1");
    };
```

### Attempted fix

I tried the following fix, but it is not enough:

*imgui_te_context.cpp*
```cpp
bool ImGuiTestContext::CaptureAddWindow(ImGuiTestRef ref)
{
    ImGuiWindow* window = GetWindowByRef(ref);

    IM_CHECK_SILENT_RETV(window != NULL, false);
    CaptureArgs->InCaptureWindows.push_back(window);

    // Try to keep parent window visible if the window is docked: this is not enough
    ImGuiDockNode* dockNode = window->DockNode;
    if (dockNode != nullptr)
        CaptureArgs->InCaptureWindows.push_back(dockNode->HostWindow);

    return true;
}
```

**Comment by ocornut** [comment]
I pushed a fix, however this may be subject to further design decision, as currently you will get:

![capture_docked_window_0000](https://github.com/ocornut/imgui_test_engine/assets/8225057/5e596f50-95ca-44bb-a0de-00f4c52e06a9)

Technically it is inconsistent with what we usually attempt for single-window, as "Window 2" tab is visible, but one could argue as soon as you attempt to capture docked window you are capturing neighboring state either way.
