### ISSUE TITLE
Test suite can't find ImGui Git branch if it's not on HEAD

### ISSUE THREAD

**Issue by SamuMazzi** [ocornut/imgui_test_engine#42]
**How to reproduce**
Execute a `git checkout` on an arbitrary commit for ImGui (in my case I went back to the 1.90.1 version) and then execute `./imgui_test_suite -gui`

In a summary:
```
cd imgui
git checkout d6cb3c9
cd ../imgui_test_engine/imgui_test_suite
make clean all
./imgui_test_suite -gui
```

**Effects**
This will break the execution in the line 839 of the file `imgui_te_utils.cpp` because the file `imgui/.git/HEAD` hasn't the hardcoded pattern `const char prefix[] = "ref: refs/heads/";` but only the hash of the commit. 
It doesn't crash but it prints the message `Dear ImGui git repository was not found.`

**Comment by ocornut** [comment]
Thank you, this should now be fixed with cbc0dac.
