### ISSUE TITLE
Compile error for IMGUI_VERSION_NUM < 18837

### ISSUE THREAD

**Issue by mgerhardy** [ocornut/imgui_test_engine#50]
```cpp
#if IMGUI_VERSION_NUM >= 18837
    bool run = ImGui::Button("Run") || ImGui::Shortcut(ImGuiMod_Ctrl | ImGuiKey_R);
#else
    bool = ImGui::Button("Run");
#endif
```

the variable is missing here - this is in `imgui_te_ui.cpp` line 283

**Comment by ocornut** [comment]
Thank you!
I have pushed a series of fixes 291b9b8 to compile latest test engine with 18837 .
Not that test suite is not exercised without it would be too much code to keep latest test suite run on older imgui.

Please note that as per https://github.com/ocornut/imgui_test_engine/wiki/Overview :
> It is expected that updates to imgui and imgui_test_engine are synchronized to similar dates (old versions of imgui_test_engine may not work with newer versions of Dear ImGui, and vice-versa).

So while we'll be putting some effort to ensure it mostly/hopefully work, it's possible that we occasionally encounter imgui/ side changes that are too difficult to maintain old version support in test_engine/ and then an imgui update would be required to match.
