### ISSUE TITLE
ImGuiTestEngine_QueueTests has a default value for filter_str as NULL

### ISSUE THREAD

**Issue by mgerhardy** [ocornut/imgui_test_engine#51]
... but `ImGuiTestEngine_PassFilter` asserts if `filter_str` is `NULL`

I wonder if `filter_str` is null, but `ImGuiTestGroup` is e.g. `ImGuiTestGroup_Tests`, the `filter_str` should be automatically set to `"tests"` (as found in the docs for `ImGuiTestEngine_PassFilter`) in `ImGuiTestEngine_QueueTests`

**Comment by ocornut** [comment]
> ... but ImGuiTestEngine_PassFilter asserts if filter_str is NULL

Fixed by 3a8a2b8, thanks!

> I wonder if filter_str is null, but ImGuiTestGroup is e.g. ImGuiTestGroup_Tests, the filter_str should be automatically set to "tests" (as found in the docs for ImGuiTestEngine_PassFilter) in ImGuiTestEngine_QueueTests

It isn't necessary because `ImGuiTestEngine_QueueTests()` will already compare group.
In fact there is a bit of redundancy here, which could be cleaned later but seems harmless.

**Comment by mgerhardy** [comment]
looks like this isn't pushed yet?
