### ISSUE TITLE
Status member variable name #define conflict (Linux)

### ISSUE THREAD

**Issue by pr0g** [ocornut/imgui_test_engine#54]
I ran into a slightly strange error when compiling `imgui_test_engine` on Linux (Ubuntu) which is shown below.

```bash
...include/imgui_te_engine.h:386:44: error: expected unqualified-id before ‘=’ token
  386 |     ImGuiTestStatus                 Status = ImGuiTestStatus_Unknown;
      |                                            ^
```

After some head scratching, I realized the issue is there happens to be another library on Linux (most likely X11) that somewhere has a define for a value called `Status`.

As a workaround, it's possible to add the following to the top of `imgui_te_engine.h`

```c++
#if defined(Status)
#  undef Status
#endif // defined(Status)
```

Another workaround which is also a bit of a pain is to rename the variable `Status` to something else, like `TestStatus`, to avoid this particular conflict.

The final option is to do nothing in the library, and just to add the `undef Status` around the include for `imgui_te_engine.h` (what I'm doing for now).

```c++
#if defined(Status)
#  undef Status
#endif // defined(Status)

#include <imgui_te_engine.h>
#include <imgui_te_exporters.h>
#include <imgui_te_ui.h>
```

Feel free to close this if this isn't a major concern and this platform isn't one that is supported, I just wanted to report this in case it's helpful.

Thanks very much for your time!

**Comment by ocornut** [comment]
Hello,
Could you find where this `#define Status` comes from?

**Comment by pr0g** [comment]
Hey there :wave: 

I was able to track it down by searching for `#define Status` in the `/usr/include` folder on Linux (Ubuntu 2204).

This was using the brilliant [ripgrep](https://github.com/BurntSushi/ripgrep) with the command `rg "#define Status" -F`

It was as predicted, X11 :confounded: 

```
X11/Xwindows.h
71:#define Status wStatus
78:#define Status int

X11/Xlib.h
83:#define Status int

X11/Xwinsock.h
51:#define Status wStatus
57:#define Status int
```

I believe this likely gets pulled in from another library I'm using (possibly SDL 2 or bgfx) and causes this conflict. It's not the end of the world as using the `undef Status` trick is working fine, it's just one of those things others might bump into in future potentially :sweat_smile: 

Thanks!


Tom

**Comment by ocornut** [comment]
I added the workaround in main library for now. Thanks! ef072b2

**Comment by pr0g** [comment]
That's awesome! Thank you very much @ocornut, much appreciated 🙂❤️
