### ISSUE TITLE
New ImGuiChildFlags_Borders define missing in most translation units

### ISSUE THREAD

**Issue by alektron** [ocornut/imgui_test_engine#57]
The very recently added `#define ImGuiChildFlags_Borders` is used in several .cpp files of imgui_test_suite but only defined in `imgui_tests_widgets.cpp` and `imgui_tests_core.cpp` (32042ba).
Therefore compilation fails.

Not sure how that wasn't caught by the checks. Or better, it was caught by the checks for 32042ba, then fixed in 32042ba. But only for `core` and `widgets`. 32042ba also introduced more usages of ImGuiChildFlags_Borders but once again is missing the defines.
This time it wasn't caught by the checks at all.

EDIT:
I just noticed that this is only an issue for older version of imgui where new flag `ImGuiChildFlags_Borders` is still called `ImGuiChildFlags_Border`. For newer versions where the flag is already called ImGuiChildFlags_Borders, the macro is not necessary and all is well. This also explains why the build checks were successful.

**Comment by ocornut** [comment]
I pushed a fix deae5220
Generally for the records:
- We try to make TestEngine compile and work with older versions of ImGui.
- BUT we generally don't try very hard to make TestSuite compile, let alone work with older versions of ImGui. The `IMGUI_VERSION_NUM` checks in TestSuite are mostly intended as documentation.

That said, today's TestSuite
