### ISSUE TITLE
Use imgui_test_engine for script automation testing

### ISSUE THREAD

**Issue by wangxinghui1** [ocornut/imgui_test_engine#58]
I am now using imgui_test_engine to automate the testing of my IMGUI application. I downloaded the latest version of the imgui library and the imgui_test_engine library and added them to my newly created project. However, I found that some methods were missing when I ran it. I don't know if I am doing it right now. I only copied the imgui_test_engine under the imgui_test_engine-main folder, and did not copy and add the others. Please give me some advice. In other words, I want to automate an imgui application. Which files should I download and add to make it run?

**Comment by wangxinghui1** [comment]
Is the shared C++ helpers for apps file required?

**Comment by wangxinghui1** [comment]
This is my error 1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(1061,44): error C2065: "ImGuiItemStatusFlags_Openable": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(1061,110): error C2065: "ImGuiItemStatusFlags_Opened": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2697,63): error C2065: "ImGuiItemStatusFlags_Checkable": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2699,63): error C2065: "ImGuiItemStatusFlags_Openable": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2771,33): error C2065: "ImGuiItemStatusFlags_Opened": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2777,37): error C2065: "ImGuiItemStatusFlags_Opened": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2781,41): error C2065: "ImGuiItemStatusFlags_Opened": Undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2785,45): error C2065: “ImGuiItemStatusFlags_Opened”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2795,33): error C2065: “ImGuiItemStatusFlags_Opened”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2799,37): error C2065: “ImGuiItemStatusFlags_Opened”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2804,41): error C2065: "ImGuiItemStatusFlags_Opened": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2813,33): error C2065: "ImGuiItemStatusFlags_Checkable": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2813,89): error C2065: "ImGuiItemStatusFlags_Checked": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2822,33): error C2065: "ImGuiItemStatusFlags_Checkable": Undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2822,88): error C2065: “ImGuiItemStatusFlags_Checked”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2854,48): error C2065: “ImGuiItemStatusFlags_Openable”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2871,41): error C2065: “ImGuiItemStatusFlags_Openable”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2871,95): error C2065: "ImGuiItemStatusFlags_Opened": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2926,41): error C2065: "ImGuiItemStatusFlags_Checkable": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2926,97): error C2065: "ImGuiItemStatusFlags_Checked": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2934,41): error C2065: "ImGuiItemStatusFlags_Checkable": Undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2934,96): error C2065: “ImGuiItemStatusFlags_Checked”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2942,41): error C2065: “ImGuiItemStatusFlags_Openable”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2942,96): error C2065: “ImGuiItemStatusFlags_Opened”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2950,72): error C2065: "ImGuiItemStatusFlags_Openable": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(2950,126): error C2065: "ImGuiItemStatusFlags_Opened": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(3187,32): error C2065: "ImGuiItemStatusFlags_Checked": undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(3194,32): error C2065: "ImGuiItemStatusFlags_Opened": Undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(3207,9): error C2065: “ImGuiItemStatusFlags_Checked”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(3342,33): error C2065: “ImGuiItemStatusFlags_Opened”: undeclared identifier
1>D:\App_ExamTest1\imgui_test_engine\imgui_te_context.cpp(3391,38): error C2065: “ImGuiItemStatusFlags_Checkable”: undeclared identifier

**Comment by ocornut** [comment]
Hello,

As per instruction in https://github.com/ocornut/imgui_test_engine/wiki/Setting-Up#building

"Add to your imconfig file #include "imgui_te_imconfig.h" or add equivalent configuration directives."

The main imgui library needs to be compiled with `#define IMGUI_ENABLE_TEST_ENGINE` and a few other options listed in `imgui_te_imconfig.h`. So it's simpler if you include this from your imconfig.h file.

**Comment by wangxinghui1** [comment]
Thank you, my problem has been solved

**Comment by wangxinghui1** [comment]
Hello, I have another question. I am now running my packaged IMGUI application. My application can be opened in my main program. At the same time, I wrote the test case, but after running my script code, I found that I It only opened my application but did not run the test script example I wrote. Which function do I need to use to run my test case? This is my complete code.

`
#include "imgui.h"
#include "imgui_test_engine/imgui_te_engine.h"
#include "imgui_test_engine/imgui_te_context.h"

#include <iostream>
#include <cstdlib>
#include <thread>
#include <chrono>
#include <windows.h>
// Function to register your test cases
extern void RegisterAppMinimalTests(ImGuiTestEngine* engine);

int main(int argc, char** argv)
{
    IM_UNUSED(argc);
    IM_UNUSED(argv);

    // Step 1: Launch your pre-built application
   const char* app_path = "D://PlanarCT//planarTestGui.exe";
    STARTUPINFO si = { sizeof(si) };
    PROCESS_INFORMATION pi;

    if (!CreateProcess(app_path, NULL, NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi))
    {
        std::cerr << "Failed to launch the application." << std::endl;
        return 1;
    }
    ImGui::CreateContext();
    // Step 2: Initialize the ImGui Test Engine
    ImGuiTestEngine* engine = ImGuiTestEngine_CreateContext();
    ImGuiTestEngineIO& test_io = ImGuiTestEngine_GetIO(engine);
    test_io.ConfigVerboseLevel = ImGuiTestVerboseLevel_Info;
    test_io.ConfigVerboseLevelOnError = ImGuiTestVerboseLevel_Debug;
    test_io.ConfigRunSpeed = ImGuiTestRunSpeed_Cinematic;

    // Optional: Save test output in junit-compatible XML format.
    // test_io.ExportResultsFile = "./results.xml";
    // test_io.ExportResultsFormat = ImGuiTestEngineExportFormat_JUnitXml;

    // Step 3: Start the ImGui Test Engine
    ImGuiTestEngine_Start(engine, ImGui::GetCurrentContext());
    ImGuiTestEngine_InstallDefaultCrashHandler();
    // Step 4: Register test cases
    RegisterAppMinimalTests(engine);

    // Give the application some time to initialize (adjust as needed)
    std::this_thread::sleep_for(std::chrono::seconds(5));

    // Step 5: Main testing loop
    while (true)
    {
        while (true)
        {
            //ImGui::NewFrame();
          //  ImGuiTestEngine_RunFrame(engine);
            if (ImGuiTestEngine_TryAbortEngine(engine))
                break;
        }
        // Here you would implement the logic to interact with the running application,
        // such as sending input or verifying GUI states.
        // Optionally: Capture frames, check application status, etc.
    }

    // Step 6: Clean up
    ImGuiTestEngine_Stop(engine);
    ImGui::DestroyContext();
    ImGuiTestEngine_DestroyContext(engine);
    // Close the application process
    /*TerminateProcess(pi.hProcess, 0);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);*/
    return 0;
}
`
`// dear imgui
// Demo Tests demonstrating the Dear ImGui Test Engine

#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui.h"
#include "imgui_internal.h"
#include "imgui_test_engine/imgui_te_context.h"
#include "imgui_test_engine/imgui_capture_tool.h"

void RegisterAppMinimalTests(ImGuiTestEngine* e)
{
    ImGuiTest* t = NULL;
------------------------------------------------------------

    t = IM_REGISTER_TEST(e, "demo_tests", "test1");
    //testpingmianct
    t->TestFunc = [](ImGuiTestContext* ctx)
        {
            ctx->SetRef("Dear ImGui VTKViewer Example");
            ctx->ItemClick("CLI_TEST_GUI");
            ctx->ItemOpen("Tube"); // Optional as ItemCheck("Node/Checkbox") can do it automatically
            ctx->ItemClick("Tube/startExposure");
            ctx->ItemClick("Tube/stopExposure");
        };
}
`
Attached is a screenshot that I have successfully run my application. My question here is whether you have provided a function to run my test case, such as void ImGuiTestEngine_RunFrame(ImGuiTestEngine* engine);
This is the opinion chatgpt gave when I asked it. I copied it into my code, but it said there is no such function, so do I need to customize a function that can run my test engine? I look forward to your reply.
![1](https://github.com/user-attachments/assets/c906e5b2-a5e5-4100-a78e-959f5a9fd1de)

**Comment by wangxinghui1** [comment]
![2](https://github.com/user-attachments/assets/8ccf298a-6b80-4629-ade6-01089e5ae617)

**Comment by ocornut** [comment]
Please do not ask chatgpt, it’s hallucinating all the time.
Read the minimal app code, wiki and browse the imgui_te_engine.h header file to get started.

You can use the Test Engine UI to manually browse and queue tests. Start with this as it is likely you have done something wrong if you used ChatGPT instead of available examples.

You can use ImGuiTestEngine_QueueTest() or ImGuiTestEngine_QueueTests() to programmatically queue tests then.

Please also next time open a new issue for separate questions.
Thanks!
